// Dummy data only. Replace with API data once the backend is ready.
// See src/services/learningSpaceService.js for the integration point.

export const learningSpaces = [
  {
    id: "ml",
    name: "Machine Learning",
    category: "Computer Science",
    description:
      "Learn ML concepts, algorithms, and build intelligent models.",
    icon: "bot",
    colorId: "purple",
    topicsTotal: 25,
    topicsCompleted: 16,
    topicsInProgress: 6,
    topicsNotStarted: 3,
    progress: 65,
    status: "In Progress",
  },
  {
    id: "data-structures",
    name: "Data Structures",
    category: "Computer Science",
    description:
      "Master arrays, trees, graphs, and core data structure fundamentals.",
    icon: "code2",
    colorId: "green",
    topicsTotal: 18,
    topicsCompleted: 8,
    topicsInProgress: 5,
    topicsNotStarted: 5,
    progress: 45,
    status: "In Progress",
  },
  {
    id: "database-systems",
    name: "Database Systems",
    category: "Computer Science",
    description: "Understand relational design, SQL, indexing, and joins.",
    icon: "database",
    colorId: "blue",
    topicsTotal: 20,
    topicsCompleted: 15,
    topicsInProgress: 4,
    topicsNotStarted: 1,
    progress: 75,
    status: "In Progress",
  },
  {
    id: "operating-systems",
    name: "Operating Systems",
    category: "Computer Science",
    description: "Study processes, memory management, and scheduling.",
    icon: "settings",
    colorId: "orange",
    topicsTotal: 16,
    topicsCompleted: 5,
    topicsInProgress: 4,
    topicsNotStarted: 7,
    progress: 30,
    status: "In Progress",
  },
  {
    id: "computer-networks",
    name: "Computer Networks",
    category: "Computer Science",
    description: "Explore protocols, routing, and network architecture.",
    icon: "globe",
    colorId: "red",
    topicsTotal: 14,
    topicsCompleted: 9,
    topicsInProgress: 3,
    topicsNotStarted: 2,
    progress: 60,
    status: "Completed",
  },
  {
    id: "web-development",
    name: "Web Development",
    category: "Design",
    description: "Build modern, responsive interfaces end to end.",
    icon: "monitor",
    colorId: "amber",
    topicsTotal: 22,
    topicsCompleted: 18,
    topicsInProgress: 3,
    topicsNotStarted: 1,
    progress: 80,
    status: "Completed",
  },
];

export const getLearningSpaceById = (id) =>
  learningSpaces.find((space) => space.id === id);
