services:
  - type: web
    name: college-project-backend
    env: node
    rootDir: backend
    buildCommand: npm install --foreground-scripts && npx --yes prisma generate
    startCommand: npm start
