// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'b4a3c6fea33ea67d7e78fe232d0f323ff37b63f3c29960fbc3d9831b54733bbd'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AttemptAnswers: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly quizAttemptId: CodecTypes['pg/int4@1']['output'];
      readonly questionId: CodecTypes['pg/int4@1']['output'];
      readonly selectedAnswer: CodecTypes['pg/text@1']['output'];
    };
    readonly LearningSpaces: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
    };
    readonly Questions: {
      readonly questionId: CodecTypes['pg/int4@1']['output'];
      readonly quizId: CodecTypes['pg/int4@1']['output'];
      readonly questionText: CodecTypes['pg/text@1']['output'];
      readonly correctAnswer: CodecTypes['pg/text@1']['output'];
    };
    readonly QuizAttempts: {
      readonly quizAttemptId: CodecTypes['pg/int4@1']['output'];
      readonly quizId: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly attemptedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly score: CodecTypes['pg/int4@1']['output'];
    };
    readonly Quizzes: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly learningSpaceId: CodecTypes['pg/int4@1']['output'];
      readonly topic: Varchar<100>;
      readonly difficulty: Varchar<20>;
      readonly quizType: Varchar<20>;
    };
    readonly Recommendations: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly recommendationType: Varchar<50>;
      readonly recommendation: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Timetables: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly day: Varchar<20>;
      readonly subject: Varchar<100>;
      readonly startTime: CodecTypes['pg/time-temporal@1']['output'];
      readonly endTime: CodecTypes['pg/time-temporal@1']['output'];
    };
    readonly Users: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
      readonly email: Varchar<255>;
      readonly passwordHash: Varchar<255>;
      readonly phoneNumber: Varchar<20> | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AttemptAnswers: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly quizAttemptId: CodecTypes['pg/int4@1']['input'];
      readonly questionId: CodecTypes['pg/int4@1']['input'];
      readonly selectedAnswer: CodecTypes['pg/text@1']['input'];
    };
    readonly LearningSpaces: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Questions: {
      readonly questionId: CodecTypes['pg/int4@1']['input'];
      readonly quizId: CodecTypes['pg/int4@1']['input'];
      readonly questionText: CodecTypes['pg/text@1']['input'];
      readonly correctAnswer: CodecTypes['pg/text@1']['input'];
    };
    readonly QuizAttempts: {
      readonly quizAttemptId: CodecTypes['pg/int4@1']['input'];
      readonly quizId: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly attemptedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly score: CodecTypes['pg/int4@1']['input'];
    };
    readonly Quizzes: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly learningSpaceId: CodecTypes['pg/int4@1']['input'];
      readonly topic: CodecTypes['sql/varchar@1']['input'];
      readonly difficulty: CodecTypes['sql/varchar@1']['input'];
      readonly quizType: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Recommendations: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly recommendationType: CodecTypes['sql/varchar@1']['input'];
      readonly recommendation: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Timetables: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly day: CodecTypes['sql/varchar@1']['input'];
      readonly subject: CodecTypes['sql/varchar@1']['input'];
      readonly startTime: CodecTypes['pg/time-temporal@1']['input'];
      readonly endTime: CodecTypes['pg/time-temporal@1']['input'];
    };
    readonly Users: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly passwordHash: CodecTypes['sql/varchar@1']['input'];
      readonly phoneNumber: CodecTypes['sql/varchar@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly attempt_answers: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly question_id: CodecTypes['pg/int4@1']['output'];
      readonly quiz_attempt_id: CodecTypes['pg/int4@1']['output'];
      readonly selected_answer: CodecTypes['pg/text@1']['output'];
    };
    readonly learning_spaces: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
      readonly user_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly questions: {
      readonly correct_answer: CodecTypes['pg/text@1']['output'];
      readonly question_id: CodecTypes['pg/int4@1']['output'];
      readonly question_text: CodecTypes['pg/text@1']['output'];
      readonly quiz_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly quiz_attempts: {
      readonly attempted_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly quiz_attempt_id: CodecTypes['pg/int4@1']['output'];
      readonly quiz_id: CodecTypes['pg/int4@1']['output'];
      readonly score: CodecTypes['pg/int4@1']['output'];
      readonly user_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly quizzes: {
      readonly difficulty: Varchar<20>;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly learning_space_id: CodecTypes['pg/int4@1']['output'];
      readonly quiz_type: Varchar<20>;
      readonly topic: Varchar<100>;
    };
    readonly recommendations: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly recommendation: CodecTypes['pg/text@1']['output'];
      readonly recommendation_type: Varchar<50>;
      readonly user_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly timetables: {
      readonly day: Varchar<20>;
      readonly end_time: CodecTypes['pg/time-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly start_time: CodecTypes['pg/time-temporal@1']['output'];
      readonly subject: Varchar<100>;
      readonly user_id: CodecTypes['pg/int4@1']['output'];
    };
    readonly users: {
      readonly email: Varchar<255>;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
      readonly password_hash: Varchar<255>;
      readonly phone_number: Varchar<20> | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly attempt_answers: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly question_id: CodecTypes['pg/int4@1']['input'];
      readonly quiz_attempt_id: CodecTypes['pg/int4@1']['input'];
      readonly selected_answer: CodecTypes['pg/text@1']['input'];
    };
    readonly learning_spaces: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly questions: {
      readonly correct_answer: CodecTypes['pg/text@1']['input'];
      readonly question_id: CodecTypes['pg/int4@1']['input'];
      readonly question_text: CodecTypes['pg/text@1']['input'];
      readonly quiz_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly quiz_attempts: {
      readonly attempted_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly quiz_attempt_id: CodecTypes['pg/int4@1']['input'];
      readonly quiz_id: CodecTypes['pg/int4@1']['input'];
      readonly score: CodecTypes['pg/int4@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly quizzes: {
      readonly difficulty: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly learning_space_id: CodecTypes['pg/int4@1']['input'];
      readonly quiz_type: CodecTypes['sql/varchar@1']['input'];
      readonly topic: CodecTypes['sql/varchar@1']['input'];
    };
    readonly recommendations: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly recommendation: CodecTypes['pg/text@1']['input'];
      readonly recommendation_type: CodecTypes['sql/varchar@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly timetables: {
      readonly day: CodecTypes['sql/varchar@1']['input'];
      readonly end_time: CodecTypes['pg/time-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly start_time: CodecTypes['pg/time-temporal@1']['input'];
      readonly subject: CodecTypes['sql/varchar@1']['input'];
      readonly user_id: CodecTypes['pg/int4@1']['input'];
    };
    readonly users: {
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly password_hash: CodecTypes['sql/varchar@1']['input'];
      readonly phone_number: CodecTypes['sql/varchar@1']['input'] | null;
    };
  };
};

export namespace Models {
  export type public_Users = {
    id: CodecTypes['pg/int4@1']['output'];
    name: Varchar<100>;
    email: Varchar<255>;
    passwordHash: Varchar<255>;
    phoneNumber: Varchar<20> | null;
    learningSpaces: public_LearningSpaces[];
    quizAttempts: public_QuizAttempts[];
    recommendations: public_Recommendations[];
    timetables: public_Timetables[];
    readonly [RelationKeys]?: 'learningSpaces' | 'quizAttempts' | 'recommendations' | 'timetables';
  };
  export type public_LearningSpaces = {
    id: CodecTypes['pg/int4@1']['output'];
    userId: CodecTypes['pg/int4@1']['output'];
    name: Varchar<100>;
    quizzes: public_Quizzes[];
    user: public_Users;
    readonly [RelationKeys]?: 'quizzes' | 'user';
  };
  export type public_Quizzes = {
    id: CodecTypes['pg/int4@1']['output'];
    learningSpaceId: CodecTypes['pg/int4@1']['output'];
    topic: Varchar<100>;
    difficulty: Varchar<20>;
    quizType: Varchar<20>;
    learningSpace: public_LearningSpaces;
    questions: public_Questions[];
    quizAttempts: public_QuizAttempts[];
    readonly [RelationKeys]?: 'learningSpace' | 'questions' | 'quizAttempts';
  };
  export type public_Questions = {
    questionId: CodecTypes['pg/int4@1']['output'];
    quizId: CodecTypes['pg/int4@1']['output'];
    questionText: CodecTypes['pg/text@1']['output'];
    correctAnswer: CodecTypes['pg/text@1']['output'];
    attemptAnswers: public_AttemptAnswers[];
    quiz: public_Quizzes;
    readonly [RelationKeys]?: 'attemptAnswers' | 'quiz';
  };
  export type public_QuizAttempts = {
    quizAttemptId: CodecTypes['pg/int4@1']['output'];
    quizId: CodecTypes['pg/int4@1']['output'];
    userId: CodecTypes['pg/int4@1']['output'];
    attemptedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    score: CodecTypes['pg/int4@1']['output'];
    attemptAnswers: public_AttemptAnswers[];
    quiz: public_Quizzes;
    user: public_Users;
    readonly [RelationKeys]?: 'attemptAnswers' | 'quiz' | 'user';
  };
  export type public_AttemptAnswers = {
    id: CodecTypes['pg/int4@1']['output'];
    quizAttemptId: CodecTypes['pg/int4@1']['output'];
    questionId: CodecTypes['pg/int4@1']['output'];
    selectedAnswer: CodecTypes['pg/text@1']['output'];
    question: public_Questions;
    quizAttempt: public_QuizAttempts;
    readonly [RelationKeys]?: 'question' | 'quizAttempt';
  };
  export type public_Recommendations = {
    id: CodecTypes['pg/int4@1']['output'];
    userId: CodecTypes['pg/int4@1']['output'];
    recommendationType: Varchar<50>;
    recommendation: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    user: public_Users;
    readonly [RelationKeys]?: 'user';
  };
  export type public_Timetables = {
    id: CodecTypes['pg/int4@1']['output'];
    userId: CodecTypes['pg/int4@1']['output'];
    day: Varchar<20>;
    subject: Varchar<100>;
    startTime: CodecTypes['pg/time-temporal@1']['output'];
    endTime: CodecTypes['pg/time-temporal@1']['output'];
    user: public_Users;
    readonly [RelationKeys]?: 'user';
  };
}

export declare const models: {
  public: {
    Users: Models.public_Users;
    LearningSpaces: Models.public_LearningSpaces;
    Quizzes: Models.public_Quizzes;
    Questions: Models.public_Questions;
    QuizAttempts: Models.public_QuizAttempts;
    AttemptAnswers: Models.public_AttemptAnswers;
    Recommendations: Models.public_Recommendations;
    Timetables: Models.public_Timetables;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly attempt_answers: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly quiz_attempt_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly question_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly selected_answer: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: 'attempt_answers_pkey';
              };
              uniques: readonly [
                {
                  readonly columns: readonly ['quiz_attempt_id', 'question_id'];
                  readonly name: 'uq_attempt_answers_attempt_question';
                },
              ];
              indexes: readonly [
                {
                  readonly name: 'idx_attempt_answers_question_id';
                  readonly columns: readonly ['question_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'idx_attempt_answers_quiz_attempt_id';
                  readonly columns: readonly ['quiz_attempt_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'attempt_answers';
                    readonly columns: readonly ['question_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'questions';
                    readonly columns: readonly ['question_id'];
                  };
                  readonly name: 'attempt_answers_question_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'attempt_answers';
                    readonly columns: readonly ['quiz_attempt_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'quiz_attempts';
                    readonly columns: readonly ['quiz_attempt_id'];
                  };
                  readonly name: 'attempt_answers_quiz_attempt_id_fkey';
                },
              ];
            };
            readonly learning_spaces: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: 'learning_spaces_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_learning_spaces_user_id';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'learning_spaces';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'learning_spaces_user_id_fkey';
                },
              ];
            };
            readonly questions: {
              columns: {
                readonly question_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly quiz_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly question_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly correct_answer: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['question_id'];
                readonly name: 'questions_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_questions_quiz_id';
                  readonly columns: readonly ['quiz_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'questions';
                    readonly columns: readonly ['quiz_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'quizzes';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'questions_quiz_id_fkey';
                },
              ];
            };
            readonly quiz_attempts: {
              columns: {
                readonly quiz_attempt_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly quiz_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly attempted_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                };
                readonly score: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['quiz_attempt_id'];
                readonly name: 'quiz_attempts_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_quiz_attempts_quiz_id';
                  readonly columns: readonly ['quiz_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'idx_quiz_attempts_user_id';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'quiz_attempts';
                    readonly columns: readonly ['quiz_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'quizzes';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'quiz_attempts_quiz_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'quiz_attempts';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'quiz_attempts_user_id_fkey';
                },
              ];
            };
            readonly quizzes: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly learning_space_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly topic: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly difficulty: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 20 };
                };
                readonly quiz_type: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sql/varchar@1', 'TOPIC'>;
                  };
                  readonly typeParams: { readonly length: 20 };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'quizzes_pkey' };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_quizzes_learning_space_id';
                  readonly columns: readonly ['learning_space_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'quizzes';
                    readonly columns: readonly ['learning_space_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'learning_spaces';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'quizzes_learning_space_id_fkey';
                },
              ];
            };
            readonly recommendations: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly recommendation_type: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly recommendation: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: 'recommendations_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_recommendations_user_id';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'recommendations';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'recommendations_user_id_fkey';
                },
              ];
            };
            readonly timetables: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly user_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly day: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 20 };
                };
                readonly subject: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly start_time: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-temporal@1';
                  readonly nullable: false;
                };
                readonly end_time: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'timetables_pkey' };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_timetables_user_id';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'timetables';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'timetables_user_id_fkey';
                },
              ];
            };
            readonly users: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly password_hash: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly phone_number: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 20 };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'users_pkey' };
              uniques: readonly [
                { readonly columns: readonly ['email']; readonly name: 'users_email_key' },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'Users' };
    readonly learning_spaces: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'LearningSpaces';
    };
    readonly quizzes: { readonly namespace: 'public' & NamespaceId; readonly model: 'Quizzes' };
    readonly questions: { readonly namespace: 'public' & NamespaceId; readonly model: 'Questions' };
    readonly quiz_attempts: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'QuizAttempts';
    };
    readonly attempt_answers: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AttemptAnswers';
    };
    readonly recommendations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Recommendations';
    };
    readonly timetables: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Timetables';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AttemptAnswers: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quizAttemptId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly questionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly selectedAnswer: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly question: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Questions';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['questionId'];
                  readonly targetFields: readonly ['questionId'];
                };
              };
              readonly quizAttempt: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'QuizAttempts';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['quizAttemptId'];
                  readonly targetFields: readonly ['quizAttemptId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'attempt_answers';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly quizAttemptId: { readonly column: 'quiz_attempt_id' };
                readonly questionId: { readonly column: 'question_id' };
                readonly selectedAnswer: { readonly column: 'selected_answer' };
              };
            };
          };
          readonly LearningSpaces: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
            };
            readonly relations: {
              readonly quizzes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Quizzes';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['learningSpaceId'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'learning_spaces';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'user_id' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Questions: {
            readonly fields: {
              readonly questionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quizId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly questionText: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly correctAnswer: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly attemptAnswers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AttemptAnswers';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['questionId'];
                  readonly targetFields: readonly ['questionId'];
                };
              };
              readonly quiz: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Quizzes';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['quizId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'questions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly questionId: { readonly column: 'question_id' };
                readonly quizId: { readonly column: 'quiz_id' };
                readonly questionText: { readonly column: 'question_text' };
                readonly correctAnswer: { readonly column: 'correct_answer' };
              };
            };
          };
          readonly QuizAttempts: {
            readonly fields: {
              readonly quizAttemptId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quizId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly attemptedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly score: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly attemptAnswers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AttemptAnswers';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['quizAttemptId'];
                  readonly targetFields: readonly ['quizAttemptId'];
                };
              };
              readonly quiz: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Quizzes';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['quizId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'quiz_attempts';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly quizAttemptId: { readonly column: 'quiz_attempt_id' };
                readonly quizId: { readonly column: 'quiz_id' };
                readonly userId: { readonly column: 'user_id' };
                readonly attemptedAt: { readonly column: 'attempted_at' };
                readonly score: { readonly column: 'score' };
              };
            };
          };
          readonly Quizzes: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly learningSpaceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly topic: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly difficulty: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
              readonly quizType: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
            };
            readonly relations: {
              readonly learningSpace: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'LearningSpaces';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['learningSpaceId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly questions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Questions';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['quizId'];
                };
              };
              readonly quizAttempts: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'QuizAttempts';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['quizId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'quizzes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly learningSpaceId: { readonly column: 'learning_space_id' };
                readonly topic: { readonly column: 'topic' };
                readonly difficulty: { readonly column: 'difficulty' };
                readonly quizType: { readonly column: 'quiz_type' };
              };
            };
          };
          readonly Recommendations: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly recommendationType: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly recommendation: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'recommendations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'user_id' };
                readonly recommendationType: { readonly column: 'recommendation_type' };
                readonly recommendation: { readonly column: 'recommendation' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly Timetables: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly day: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
              readonly subject: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly startTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-temporal@1' };
              };
              readonly endTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-temporal@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'timetables';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'user_id' };
                readonly day: { readonly column: 'day' };
                readonly subject: { readonly column: 'subject' };
                readonly startTime: { readonly column: 'start_time' };
                readonly endTime: { readonly column: 'end_time' };
              };
            };
          };
          readonly Users: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly phoneNumber: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
            };
            readonly relations: {
              readonly learningSpaces: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'LearningSpaces';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly quizAttempts: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'QuizAttempts';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly recommendations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Recommendations';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly timetables: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Timetables';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly email: { readonly column: 'email' };
                readonly passwordHash: { readonly column: 'password_hash' };
                readonly phoneNumber: { readonly column: 'phone_number' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
